server:
  port: 8089

spring:
  application:
    name: letterService
  datasource:
    url: jdbc:postgresql://localhost:5433/letter_request
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka